name: Rent a Buddy CI/CD
on:
  push:
    branches: [main]
jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Make mvnw executable
        run: |
          cd backend
          chmod +x mvnw  # Use relative path without ./
          ls -l mvnw    # Verify permissions (for debugging)
      - name: Build Backend JAR
        run: cd backend && ./mvnw clean package -B  # -B for non-interactive mode
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Backend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/rent-a-buddy-backend:latest backend/
          docker push ${{ secrets.DOCKER_USERNAME }}/rent-a-buddy-backend:latest
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Frontend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/rent-a-buddy-frontend:latest frontend/
          docker push ${{ secrets.DOCKER_USERNAME }}/rent-a-buddy-frontend:latest