name: Rent a Buddy CI/CD
on:
  push:
    branches: [main]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend  # Sets default directory for all run steps

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make mvnw executable and debug
        run: |
          chmod +x mvnw
          ls -l mvnw  # Check permissions in logs
          file mvnw   # Verify file type

      - name: Build Backend JAR
        run: ./mvnw clean package -B

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/rent-a-buddy-backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/rent-a-buddy-backend:latest

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Frontend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/rent-a-buddy-frontend:latest frontend/
          docker push ${{ secrets.DOCKER_USERNAME }}/rent-a-buddy-frontend:latest